created branch for design logged in tabbar and pushed a test change
Macco-Academy/chirp pull request #6
Opened 2023-06-06 15:58 UTC by kd798529

### What does this PR do?
First test commit for design logged in tabbar branch

### Description of tasks to be completed

### How to manually test

### Any background context you want to provide

### Screenshots
![image](https://github.com/Macco-Academy/chirp/assets/19350496/cc91628f-3f26-4778-994f-0cc8cda23a12)

2023-06-07 03:43 UTC, stepharski approved these changes

2023-06-07 06:52 UTC, EMacco requested changes

2023-06-07 06:52 UTC, EMacco commented on Chirp/ViewController.swift
> +class ViewController: UITabBarController {
Could we please create a new file and class instead? You can call it `HomeTabBarController`

2023-06-07 06:52 UTC, EMacco commented on Chirp/ViewController.swift
> +        let tabIconImages = ["ellipsis.message.fill", "person.2.fill", "squareshape.split.2x2"]
Can we create an extension of UIImage and add create the icons there instead?
If you pull the latest version of development and rebase, you'll notice that there's an `Extensions` folder. Inside this folder, create a new file `UIImage+Extension` and add these icons there.
E.g
```swift
extension UIImage {
    static let ellipsisMessageFill = UIImage(systemName: "ellipsis.message.fill")!
    static let personFill = UIImage(systemName: "person.2.fill")!
    ...
}
```

2023-06-07 06:52 UTC, EMacco commented on Chirp/ViewController.swift
> +            items[i].image = UIImage(systemName: tabIconImages[i])
Can we set filled images for selected state and outlined for the regular state?
```suggestion
            items[i].image = UIImage(systemName: tabIconImages[i])
            items[i].selectedImage = UIImage(systemName: tabIconSelectedImages[i])
```

2023-06-07 06:52 UTC, EMacco commented on Chirp/ViewController.swift
> +        }
Can we also set the tintColor and unSelected color to `.appBrown` and `.appBrownSecondary` You'll have access to both of these when you rebase with the latest development 
```swift
tabBar.tintColor = .brown
tabBar.unselectedItemTintColor = .lightGray
```

2023-06-07 06:52 UTC, EMacco commented on Chirp/ViewController.swift
> +}
Let's remember to remove these when the real classes are created For now we can leave it here

2023-06-08 16:13 UTC, EMacco approved these changes

2023-06-08 16:14 UTC, merged